### ISSUE TITLE
Vulnerability Factors Language - Redundant 'IT technology' and 'OT technology'

### ISSUE THREAD

**Issue by workentin** [cutaway-security/IACS_STAR_Methodology#1]
In the README section on Vulnerability Factors, I think it might make sense to change "technology" in things like:
`Remotely accessible but countermeasures protecting OT technology`
to something like:
`Remotely accessible but countermeasures protecting OT assets and systems`

**Comment by cutaway** [comment]
Roger. Will review and consider. Leaving open for now.

**Comment by cutaway** [comment]
Changing this would mean adding 'assets, systems, and communications' to ensure all things were considered. This makes the statement too long, in my opinion. So, I modified 'technology' to 'technologies' which actually makes sense.

**Comment by cutaway** [comment]
Closing
