### ISSUE TITLE
IACS Calculator Vector Score Broken Link

### ISSUE THREAD

**Issue by cutaway** [cutaway-security/IACS_STAR_Methodology#10]
Users should be able to use the vector score to repopulate the calculator. It appears this is broken or the link in the page is not generated properly.

**Comment by c-bless** [comment]
The Vector score link contains characters that are allowed in URIs but some of them ":" and "/" are only allowed in specific positions (e.g., ":" in the schema like "https:"). The Vector string is used in a parameter. Thus, it might be required to encode these characters.

**Comment by JakeSmithQUT** [comment]
Changing line 181 in iacs_star_calculator.html from

`$("#score").attr("href", "https://iacs-star-calculator.com/?vector=" + score);`

to

`$("#score").attr("href", "https://iacs-star-calculator.com/iacs_star_calculator.html?vector=" + score);`

seems to have it add to the URL correctly. Not all options seem to carry over though so there is potentially an issue with the decoding.

**Comment by c-bless** [comment]
Pull request is fixing with following approach (using a python based generator for the calculator which takes input from YAML):

submitting score vector as base64 encoded string and changed wrong abbreviations.

1. create base64 parameter via 'btoa' 
```
score_param = btoa(score)
$("#score").attr("href", "https://iacs-star-calculator.com/?vector=" + score_param);
```
2. decode parameter via 'atob' 
```
init(atob(getUrlParameter('vector')), getUrlParameter('v'));
```
3. fixed wrong abbreviations for div id numbers (not all were correct. Thus the values were not republished properly)
```
var partials = ["sl", "m", "o", "a", "ea", "ee", "aw", "dr", "lc", "li", "la", "lac", "ed", "pd", "se", "r"];
```




Added an addition variable to template file {{ filename }} that is set via the python script. The value is taken from filename variable of the YAML file which is referring the output filename. 

in YAML:
```
outfile:
  #specifing the filename of the output file that will be created in output folder "html"
  filename: iacs_star_calculator.html
```

in template:
```
$("#score").attr("href", "https://iacs-star-calculator.com/{{filename}}?vector=" + score_param);
```
                        
in output:
```
$("#score").attr("href", "https://iacs-star-calculator.com/iacs_star_calculator.html?vector=" + score_param);
```
