### ISSUE TITLE
Threat Actor Factors - Size - Options 3 and 5 description is the same

### ISSUE THREAD

**Issue by JakeSmithQUT** [cutaway-security/IACS_STAR_Methodology#12]
Duplicate level description for selections 3 and 5 with _Size_ drop-down under _Threat Actor Factors_ column

3 - Remote owner/operator users
5 - Remote owner/operator users

![image](https://github.com/cutaway-security/IACS_STAR_Methodology/assets/38513306/0d9528a6-ecf2-4c3e-a7f7-925b71a53121)

**Comment by cutaway** [comment]
Noted. Updated in 'weber-dev' branch and preparing for review to pull into 'main'

**Comment by cutaway** [comment]
This issue was addressed in the last revision. Closing and thank you
