### ISSUE TITLE
Dropdown field for "Motive" showing options from "Opportunity"

### ISSUE THREAD

**Issue by c-bless** [cutaway-security/IACS_STAR_Methodology#4]
The drop-down field for "_Motive_" in Section "_Threat Actor Factors_" showing options from "_Opportunity_" . The option for "_Motive_" differ from the options described in the PDF document.

**Comment by cutaway** [comment]
Nice catch @c-bless . I have updated the calculator and fixed a bunch of typos.

Just noticed your pull request. I updated before I saw it. Plus, I don't like putting the N/A in there as it makes it seem like it is not selectable. Each value is selectable should the team not like the other statements and feel the selection is valid.
